name: 'Install Linux Dependencies'
runs:
  using: "composite"
  steps:
    - name: Free HDD space
      shell: bash
      run: |
        echo "Listing 20 largest packages"
        dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 20
        df -h
        sudo apt-get update
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^temurin-.*'
        sudo apt-get remove -y azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox powershell mono-devel
        sudo apt-get autoremove -y
        sudo apt-get clean
        df -h
        echo "Removing large directories"
        # deleting 15GB
        sudo rm -rf /usr/share/dotnet/
        sudo rm -rf /usr/local/lib/android
        df -h
    - name: Add LLVM Debian repository
      uses: myci-actions/add-deb-repo@11
      with:
        repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-20 main
        repo-name: llvm-repo
        keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
    - name: Update and upgrade APT
      shell: bash
      run: sudo apt-get update && sudo apt-get upgrade -y
    - name: Install LLVM
      shell: bash
      run: sudo apt-get install llvm-20 llvm-20-dev llvm-20-runtime clang-20 clang-tools-20 lld-20 libpolly-20-dev libmlir-20-dev mlir-20-tools
