[package]
name = "scarb-native-dump"
edition.workspace = true

[dependencies]
anyhow.workspace = true
cairo-lang-sierra.workspace = true
cairo-native.workspace = true
melior.workspace = true
scarb-metadata.workspace = true
serde_json.workspace = true
serde.workspace = true
