[package]
name = "debug_utils"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
cairo-lang-starknet-classes.workspace = true
serde_json = "1.0.135"
