[package]
name = "debug_utils"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
cairo-lang-starknet-classes.workspace = true
serde_json.workspace = true
