name: Release

permissions:
  contents: write
  discussions: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
        MLIR_SYS_180_PREFIX: /usr/lib/llvm-18/
        LLVM_SYS_180_PREFIX: /usr/lib/llvm-18/
        TABLEGEN_180_PREFIX: /usr/lib/llvm-18/
        CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: free HDD space
        run: |
          # deleting space
          sudo rm -rf /usr/share/dotnet/
          sudo rm -rf /usr/local/lib/android
      - name: Setup rust env
        uses: dtolnay/rust-toolchain@1.78.0
      - name: Retreive cached dependecies
        uses: Swatinem/rust-cache@v2
      - name: add llvm deb repository
        uses: myci-actions/add-deb-repo@10
        with:
          repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main
          repo-name: llvm-repo
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
      - name: Install LLVM
        run: sudo apt-get install llvm-18 llvm-18-dev llvm-18-runtime clang-18 clang-tools-18 lld-18 libpolly-18-dev libmlir-18-dev mlir-18-tools
      - name: publish the runtime
        run: cargo publish --token ${CRATES_TOKEN} --all-features -p cairo-native-runtime
      - name: publish the crate
        run: cargo publish --token ${CRATES_TOKEN} --all-features -p cairo-native
