name: Release on crates.io

permissions:
  contents: write
  discussions: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-24.04
    env:
        MLIR_SYS_200_PREFIX: /usr/lib/llvm-20/
        LLVM_SYS_201_PREFIX: /usr/lib/llvm-20/
        TABLEGEN_200_PREFIX: /usr/lib/llvm-20/
        CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: free HDD space
        run: |
          # deleting space
          sudo rm -rf /usr/share/dotnet/
          sudo rm -rf /usr/local/lib/android
      - name: Setup rust env
        uses: dtolnay/rust-toolchain@1.84.1
      - name: Retreive cached dependecies
        uses: Swatinem/rust-cache@v2
      - name: add llvm deb repository
        uses: myci-actions/add-deb-repo@11
        with:
          repo: deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-20 main
          repo-name: llvm-repo
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
      - name: Install LLVM
        run: sudo apt-get install llvm-20 llvm-20-dev llvm-20-runtime clang-20 clang-tools-20 lld-20 libpolly-20-dev libmlir-20-dev mlir-20-tools
      - name: publish sierra emu
        run: cargo publish --token ${CRATES_TOKEN} --all-features -p sierra-emu
      - name: publish cairo native
        run: cargo publish --token ${CRATES_TOKEN} --all-features -p cairo-native
